{"name": "Test of failed attempt to create a repeating user", "status": "passed", "description": "Negative test of the endpoint \"Создание пользователя\" POST /api/auth/register.Checks impossibility of creation of repeating user, that response body contains all required fields, and that request returns \"success\": false", "start": 1719670158746, "stop": 1719670159017, "uuid": "07576406-0433-4a3e-a713-cb599c6060e9", "historyId": "3e09caf90432f3186deea1c0a89bef6f", "testCaseId": "3e09caf90432f3186deea1c0a89bef6f", "fullName": "tests.test_user_creation.TestUserCreation#test_creation_repeating_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_creation"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "DESKTOP-4KK18J8"}, {"name": "thread", "value": "600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_creation"}]}